name: Build Viewer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setup environment
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: abatilo/actions-poetry@v2.0.0
    - run: poetry install
    
    # Build the viewer
    - name: Build Viewer
      run: poetry run python -m cyoa.tools.client build --input project-v15.json --output viewer
    - name: Archive Viewer
      run: tar --dereference --hard-dereference -cvf artifact.tar .
    
    # Upload the viewer artifact
    - uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: ./artifact.tar
  
  deploy:
    runs-on: ubuntu-release
    needs: build
    
    steps:
      - uses: actions/deploy-pages@v1
      - uses: actions/deploy-pages@v1
