name: 🚀 Deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: "ftp-deploy"
  cancel-in-progress: true

jobs:
  ftp-deploy-images:
    name: 📦 Upload Files
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 📂 Sync Viewer
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: viewer/
          server-dir: viewer/v17/
          state-name: .states-viewer.json

      - name: 📂 Sync Images
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: images/v17/
          server-dir: images/v17/
          state-name: .states-images.json
          
